
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FactorialService", targetNamespace = "http://service.factorial.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FactorialService {


    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "factorial", targetNamespace = "http://service.factorial.com/", className = "client.Factorial")
    @ResponseWrapper(localName = "factorialResponse", targetNamespace = "http://service.factorial.com/", className = "client.FactorialResponse")
    @Action(input = "http://service.factorial.com/FactorialService/factorialRequest", output = "http://service.factorial.com/FactorialService/factorialResponse")
    public long factorial(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
