
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FactorialServiceService", targetNamespace = "http://service.factorial.com/", wsdlLocation = "http://localhost:8081/factorialservice?wsdl")
public class FactorialServiceService
    extends Service
{

    private final static URL FACTORIALSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FACTORIALSERVICESERVICE_EXCEPTION;
    private final static QName FACTORIALSERVICESERVICE_QNAME = new QName("http://service.factorial.com/", "FactorialServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/factorialservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACTORIALSERVICESERVICE_WSDL_LOCATION = url;
        FACTORIALSERVICESERVICE_EXCEPTION = e;
    }

    public FactorialServiceService() {
        super(__getWsdlLocation(), FACTORIALSERVICESERVICE_QNAME);
    }

    public FactorialServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACTORIALSERVICESERVICE_QNAME, features);
    }

    public FactorialServiceService(URL wsdlLocation) {
        super(wsdlLocation, FACTORIALSERVICESERVICE_QNAME);
    }

    public FactorialServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACTORIALSERVICESERVICE_QNAME, features);
    }

    public FactorialServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FactorialServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FactorialService
     */
    @WebEndpoint(name = "FactorialServicePort")
    public FactorialService getFactorialServicePort() {
        return super.getPort(new QName("http://service.factorial.com/", "FactorialServicePort"), FactorialService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FactorialService
     */
    @WebEndpoint(name = "FactorialServicePort")
    public FactorialService getFactorialServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.factorial.com/", "FactorialServicePort"), FactorialService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACTORIALSERVICESERVICE_EXCEPTION!= null) {
            throw FACTORIALSERVICESERVICE_EXCEPTION;
        }
        return FACTORIALSERVICESERVICE_WSDL_LOCATION;
    }

}
